# Generated by Django 4.2.7 on 2024-11-02 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 19, 5, 17, 370573, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
