# Generated by Django 4.2.7 on 2024-10-22 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 17, 26, 18, 951788, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
