# Generated by Django 4.2.7 on 2024-09-21 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 11, 46, 48, 918766, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
