# Generated by Django 4.2.7 on 2024-09-24 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_flight_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_cosmodrom',
            field=models.CharField(blank=True, null=True, verbose_name='Космодром прибытия'),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_launch_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемая дата запуска'),
        ),
        migrations.AddField(
            model_name='flight',
            name='launch_cosmodrom',
            field=models.CharField(blank=True, null=True, verbose_name='Космодром запуска'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 6, 56, 5, 288478, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='shipflight',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.flight'),
        ),
        migrations.AlterField(
            model_name='shipflight',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.ship'),
        ),
        migrations.AlterModelTable(
            name='shipflight',
            table='ship_flight',
        ),
    ]
