# Generated by Django 4.2.7 on 2024-11-04 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_value_shipflight_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 8, 20, 33, 44247, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
