# Generated by Django 4.2.7 on 2024-09-24 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_flight_arrival_cosmodrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 7, 2, 58, 145433, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
