# Generated by Django 4.2.7 on 2024-09-25 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 9, 13, 44, 946823, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
