# Generated by Django 4.2.7 on 2024-10-17 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 7, 35, 36, 849954, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
