# Generated by Django 4.2.7 on 2024-11-04 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_flight_result_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 12, 56, 49, 530295, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
