# Generated by Django 4.2.7 on 2024-10-06 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 16, 39, 46, 607481, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
